name: ci

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: "Enable tmate debug"
        type: boolean
        default: "false"

jobs:
  check-semantic-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Set fetch-depth to 0 to fetch all tags (necessary for `git-mkver` to determine the correct semantic version).
          fetch-depth: 0
      - uses: octue/check-semantic-version@1.0.0.beta-3
        with:
          path: pyproject.toml
          breaking_change_indicated_by: minor
